[package]
name = "bevy_coordinate_systems"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
bevy_basic_camera = { git = "https://github.com/DGriffin91/bevy_basic_camera" }
