[package]
name = "bevy_coordinate_systems"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10.1"

[dev-dependencies]
bevy_basic_camera = { git = "https://github.com/DGriffin91/bevy_basic_camera" }
